[build]
command = "npm run build"
functions = "out_functions"
publish = "out_publish"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NODE_VERSION = "v16.20.2"
NPM_VERSION = "8.19.4"
SITE_URL = "https://blog-nextjs-course.netlify.app"

[[plugins]]
package = "@netlify/plugin-nextjs"
