[build]
command = "npm run deploy:static && echo SITE_URL: $SITE_URL"
publish = "out/"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NODE_VERSION = "v16.20.2"
NPM_VERSION = "8.19.4"
SITE_URL = "https://main--blog-nextjs-course.netlify.app"

[[plugins]]
package = "@netlify/plugin-nextjs"
